services:
  notificationService-api:
    image: notification-service-api
    build:
      dockerfile: NotificationService.Api/Dockerfile
    ports:
      - "10500:80"
      - "10501:443"
    environment:
      - AuthSettings__BaseUrl=https://host.docker.internal:9001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+80;https://+443
    entrypoint:
      - "dotnet"
      - "NotificationService.Api.dll"
    networks:
      - notification-network
      - authService-network
  redis:
    image: redis:alpine
    container_name: notificationService-redis
    ports:
      - "10550:6379"
    volumes:
      - notification_redis_data:/var/lib/redis/data
    restart:
      unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 50s
      timeout: 2s
      retries: 5
    networks:
      - notification-network

volumes:
  notification_redis_data:

networks:
  notification-network:
    driver: bridge
  authService-network:
    external: true  
